# SPDX-FileCopyrightText: 2023 SBB AG
#
# SPDX-License-Identifier: CC0-1.0

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
